services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "400m"
        max-file: "5"
