openapi: 3.0.0
info:
  title: Perp API
  version: 1.0.0

paths:

  /perp_start:
    get:
      summary: Start perpetual trading strategy
      description: |
        Starts the perpetual trading strategy
      responses:
        "200":
          description: Successful start response
          content:
            application/json:
              schema:
                type: object
                description: Result returned by `_perp_start` function
                additionalProperties: true
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error

