name: Deploy GMX Bot

on:
  push:
    branches: [main, multiwallet]
env:
  PROJECT_ID: xtreamly-ai
  REGION: europe-west1
  SERVICE_NAME: xtreamly-gmx-bot
  REPOSITORY: xtreamly-gmx-bot

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/multiwallet'
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/664616721985/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: "github-actions-sa@xtreamly-ai.iam.gserviceaccount.com"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE_URL="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/xtreamly-gmx-bot:${IMAGE_TAG}"
          LATEST_IMAGE_URL="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/xtreamly-gmx-bot:latest"

          docker buildx build --platform linux/amd64 -t $IMAGE_URL -t $LATEST_IMAGE_URL --push .

          echo "Pushed image to $IMAGE_URL and $LATEST_IMAGE_URL"

      - name: Get Xtreamly AI Service URL
        run: |
          XTREAMLY_API_BASE_URL=$(gcloud run services describe xtreamly-api --region=${{ env.REGION }} --format='value(status.url)')
          echo "XTREAMLY_API_BASE_URL=$XTREAMLY_API_BASE_URL" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run services update ${{ env.SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/xtreamly-gmx-bot:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --platform=managed \
            --set-env-vars="NODE_ENV=production,GCP_PROJECT_ID=xtreamly-ai,GCP_REGION=europe-west1,GOOGLE_CLOUD_PROJECT=xtreamly-ai,MONITORING_DB_NAME=bot_events,XTREAMLY_API_BASE_URL=${{ env.XTREAMLY_API_BASE_URL }}" \
            --set-secrets="DB_HOST=DB_HOST:latest,DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_PORT=DB_PORT:latest,DB_NAME=DB_NAME:latest,ARB_RPC_URL=ARB_RPC_URL:latest,USER_MANAGEMENT_DB_NAME=USER_MANAGEMENT_DB_NAME:latest,SENTRY_DSN=SENTRY_DSN_XTREAMLY_GMX_BOT:latest,MIN_WALLET_FOR_YIELD=MIN_WALLET_FOR_YIELD:latest,YIELD_GENERATION_URL=YIELD_GENERATION_URL:latest"

      - name: Verify deployment
        run: |
          # Get the Cloud Run service URL
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --format='value(status.url)')
          echo "Service URL: $SERVICE_URL"

          # Wait for service to be ready
          sleep 30

          # Test health endpoint (if available)
          curl -f "$SERVICE_URL/health" || echo "Health endpoint not available, but deployment completed"
          echo "Deployment successful!"
